sudo: required
language: bash
services:
  - docker

env:
  global:
    - INSP_VERSION=v2.0.25

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get install -y openssl parallel


script:
  # Create swarm for explicit testing
  # Make sure that there is a useable ip address as "advertise address" because else the swarm creation fails maybe
  - docker swarm init --advertise-addr `ip addr s | grep global | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -n1`
  # Initial build with default parameters
  - docker build --build-arg VERSION="${INSP_VERSION}" -t inspircd:testing .
  # Run all tests from test directory
  - ls tests/*.sh | parallel --joblog /tmp/joblog
  - cat /tmp/joblog

after_success:
  # Push successful builds of the master branch to Docker Hub
  # You need to define $DOCKER_REPO_PREFIX, $DOCKER_REPO_NAME, $DOCKER_USERNAME and $DOCKER_PASSWORD in your Travis settings.
  # $DOCKER_REPO_PREFIX - Organisation of username who owns the repo on Docker Hub
  # $DOCKER_REPO_NAME   - Repository name on Docker Hub
  # $DOCKER_USERNAME    - Docker Hub username used to push the image
  # $DOCKER_PASSWORD    - Password of the Docker Hub user used to push the image
  # See https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$DOCKER_REPO_PREFIX" != "" ] && [ "$DOCKER_REPO_NAME" != "" ] && [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_PASSWORD" != "" ]; then
    tools/tagging.sh "${DOCKER_REPO_PREFIX}/${DOCKER_REPO_NAME}" "${INSP_VERSION:-latest}" "";
    docker images "${DOCKER_REPO_PREFIX}/${DOCKER_REPO_NAME}";
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker images --format "{{.Repository}}:{{.Tag}}" "${DOCKER_REPO_PREFIX}/${DOCKER_REPO_NAME}" | xargs -L 1 docker push ;
    docker run --rm -v "$(pwd)/:/data/:ro" -e "DOCKERHUB_USERNAME=$DOCKER_USERNAME" -e "DOCKERHUB_PASSWORD=$DOCKER_PASSWORD" -e "DOCKERHUB_REPO_PREFIX=$DOCKER_REPO_PREFIX" -e "DOCKERHUB_REPO_NAME=$DOCKER_REPO_NAME" sheogorath/readme-to-dockerhub;
    fi
